### ISSUE TITLE
App won't leave "Welcome" screen

### ISSUE THREAD

**Issue by iansoper** [clintoncrick/Unofficial-Support-for-Trello#1]
I followed the directions on the welcome screen and authenticated via the settings link in the Pebble iOS app, but the app never leaves the welcome screen. I've tried closing and reopening the app,  uninstalling/reinstalling the app and I've tried revoking and re-authenticating the app. The app still won't go past the welcome screen.

**Comment by clintoncrick** [comment]
Thanks for the feedback, Ian! Did you use the source from GitHub, or did you install from the Pebble app store?

If you used the source from GitHub, the Trello creds are empty, and you'd need to supply those in the src/config.js file. The error handling for that is pretty much nonexistent at this point, which would explain why it stays on the Welcome screen. I'll update the read me tonight to reflect that, and add a better error screen shortly. You can generate Trello API creds at: https://trello.com/app-key

If you've installed from the Pebble app store, I believe the app still needs to go through Pebble's iOS JS bundling. My Pebble developer dashboard currently shows it as 'Waiting for JavaScript bundling on iOS,' though that also means it shouldn't show up in the iOS app.

**Comment by iansoper** [comment]
I installed it from the Pebble app store. So, does that mean the app will only work when the pebble iOS app is updated?

**Comment by iansoper** [comment]
If I install it from github, what do I use for the `API_RETURN_URL`?

**Comment by clintoncrick** [comment]
Unfortunately, yes. Pebble has to bundle the watchapp (if written in Pebble.JS, and this one is) with the iOS app, and then have that app approved by Apple. It looks like I missed the February cutoff, so I'm not sure when it'll actually make it into the Pebble iOS app.

You can find more information on JavaScript bundling here: http://developer.getpebble.com/blog/2014/04/22/JS-Bundling/

I've updated the description in the Pebble app store to reflect that it's still waiting on iOS bundling. I'll also look into why you were able to download it via iOS app if it wasn't bundled.

**Comment by clintoncrick** [comment]
You're welcome to use: http://clintoncrick.com/prello/ for that. Trello passes back the token as a hash. That page grabs the hash, and then passes it to the app
