### ISSUE TITLE
Error: "Unable to load token"

### ISSUE THREAD

**Issue by iansoper** [clintoncrick/Unofficial-Support-for-Trello#2]
I loaded the app via CloudPebble and used my Trello API key. However, when I go to run the app (after building and installing and configuring it, i get an error with the token. See the logs:

```
[PHONE] pebble-app.js:?: JS: Prello: (+) [window 1] : [window 1]
[PHONE] pebble-app.js:?: JS: Prello: (+) [card 2] : [window 1],[card 2]
[PHONE] pebble-app.js:?: JS: Prello: (-) [window 1] : [card 2]
[PHONE] pebble-app.js:?: JS: Prello: [CONFIG]: Launching configuration screen.
[PHONE] pebble-app.js:?: JS: Prello: [CONFIG]: response is back!
[PHONE] pebble-app.js:?: JS: Prello: [object Event]
[PHONE] pebble-app.js:?: JS: Prello: {"token":"d47d7ade70cb084faffc04603f91094cf7b273f467f26df17e5a79332b6a9fd8"}
[PHONE] pebble-app.js:?: JS: Prello: [ERROR!]: Unable to load token. Please reconfigure your app.
```

**Comment by clintoncrick** [comment]
Ian,

I apologize for the delay. I looked at your logs and compared them to the code, and everything _should_ work given your output. I'll continue to look into this, attempting to replicate.

Unrelated to this issue, but related to the project as a whole: the iOS version has been approved and released in the latest Pebble app update. You may have better luck installing from the Pebble app environment now that the app has been bundled on iOS.

**Comment by iansoper** [comment]
Thanks for the update. I just tried installing from the pebble app store and I'm still getting the same issue where I can't get past the welcome screen. (#1)

**Comment by stefduch** [comment]
Hi, just created a pull request that fixes this issue, so clintoncrick let me know if it looks good.

**Comment by clintoncrick** [comment]
To all: I'm iOSless and was unable to properly reproduce these on any of the Android devices. This left me at a standstill. For that, I apologize.

Thank you, @stefduch for the fix. I've accepted the pull request and built a new version. It's available in the app store. It should be available now- you'll know it's been updated as the splash screen's version reflects 1.4. I also credited you with the fix in the change log.

@iansoper: I'm going to leave this open for now. If this issue's been fixed, can you please close the thread? Thank you!

**Comment by stefduch** [comment]
@clintoncrick happy to help. Thanks for this very useful app! BTW, I installed the app store version and can confirm all issues are fixed for me (on iOS).
