### ISSUE TITLE
App settings screen is blank/not loading

### ISSUE THREAD

**Issue by omkensey** [clintoncrick/Unofficial-Support-for-Trello#3]
On my Pebble Time Steel, the app seems to load fine on my watch but when I try to go to Settings in the iOS Pebble app, I just get a blank white screen with the app name and a Cancel button at the top.

**Comment by stefduch** [comment]
I have the same issue with my Pebble Time, firmware v3.7, on iOS.

**Comment by iansoper** [comment]
I have the same issue with an original Pebble (2.9.1)

**Comment by iansoper** [comment]
Also, same issue when upgrading to Pebble Time app v3.5 and Pebble firmware v3.8

**Comment by stefduch** [comment]
Just created a pull request that fixes this issue (I have the app working on my watch), so it is up to the owner of the app to have a look and see if my fix makes sense ;)

**Comment by iansoper** [comment]
I tried it and it fixed my issue, the config screen is still blank after I authenticate (I wasn't even able to authenticate before), but he app works now.

**Comment by stefduch** [comment]
Hmm, interesting... you see the Trello authorization page and then a blank page?

**Comment by clintoncrick** [comment]
All: I've rebuilt the app using @stefduch's fix and published it to the app store. It should be available now for you to test.

@omkensey: when you get a chance, could you try the new version? If it solves the issue, would you mind closing this thread? Thanks!

@stefduch: Thank you for your help on this!

@iansoper: That's weird, though a step in the right direction. I'm unsure how to force close an authentication / setting window after information's been passed back to the app outside of what I'm already doing.

**Comment by omkensey** [comment]
Belatedly, yes, now WFM as well :)
